import 'bootstrap/dist/css/bootstrap.min.css';
import './nv.d3.min.css';
import 'react-select/dist/react-select.min.css';
import 'fixed-data-table/dist/fixed-data-table.min.css';
import ReactDOM from 'react-dom';
import React from 'react';
import customDataHandlers from './customDataHandlers';
import customStateHandlers from './customStateHandlers';
import App from './app';
import { Router, Route, browserHistory } from 'react-router';
